dist: focal
os: linux

language: python

jobs:
  include:
    - language: python
      python: 3.6
      name: "linting"
      env: TOXENV=lint
    - language: python
      python: 3.6
      name: "Test on python 3.6"
      env: TOXENV=py36
    - language: python
      python: 3.7
      name: "Test on python 3.7"
      env: TOXENV=py37
    - language: python
      python: 3.8
      name: "Test on python 3.8"
      env: TOXENV=py38
    - language: python
      python: 3.9
      name: "Test on python 3.9"
      env: TOXENV=py39
    - language: python
      python: pypy3
      name: "Test on python pypy3"
      env: TOXENV=pypy3

services:
  - mongodb

install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install coveralls
  - travis_retry pip install flake8
  - travis_retry pip install tox>=3.14
  - travis_retry pip install virtualenv

script:
  - tox

after_success:
  - coveralls --verbose

notifications:
  irc: irc.freenode.org#flask-mongoengine

# Only run builds on the master branch and GitHub releases (tagged as vX.Y.Z)
branches:
  only:
    - master
    - /^v.*$/

# Whenever a new release is created via GitHub, publish it on PyPI.
deploy:
  provider: pypi
  user: wojcikstefan
  password:
    secure: ZShEfSeu1pUHPGWtO5JAERp3nkG1omFIDxz/N+qNEJGwIRxXH6S0E17p9jaRAwrBY11F6ecajOgz1E1ICovYf8IitOP8I/CyieF6EPV7Bv4PZyKJdWGzT/Edjrt+wAjY7Kwlr2Gkh9Tu1lChZcWvhyMVPYCgqyA2yP0W2b9kC4Y=

  # create a source distribution and a pure python wheel for faster installs
  distributions: "sdist bdist_wheel"

  # only deploy on tagged commits (aka GitHub releases) and only for the
  # parent repo's builds running Python 3.6
  on:
    tags: true
    python: 3.6
    repo: MongoEngine/flask-mongoengine
